# Generated by Django 3.1 on 2021-06-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='movie',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
