# Generated by Django 3.1 on 2021-07-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210712_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='imdb',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
