# Generated by Django 3.1 on 2021-07-18 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genres', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Netflix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netflix', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Runtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtype', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
                ('votes', models.IntegerField(blank=True, null=True)),
                ('cast', models.TextField(max_length=250)),
                ('plot', models.TextField(max_length=300)),
                ('keywords', models.TextField(max_length=150)),
                ('poster', models.CharField(max_length=256)),
                ('genres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('mtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.type')),
                ('netflix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.netflix')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.rate')),
                ('runtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.runtime')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.year')),
                ('youtube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.youtube')),
            ],
        ),
    ]
