# Generated by Django 3.1 on 2021-07-18 16:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='id',
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(default=uuid.uuid4, max_length=128, primary_key=True, serialize=False, unique=True),
        ),
    ]
