# Generated by Django 3.1 on 2021-07-18 20:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210718_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
