# Generated by Django 3.1 on 2021-07-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_release'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='genres',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='plot',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='netflix',
            name='netflix',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='youtube',
            field=models.TextField(),
        ),
    ]
